server:
  port: 8010

spring:
  application:
    name: microservice-client-user-ribbon-prop
    
#user:   
  #userServicePath: http://localhost:7900/simple/

eureka:
  client:
    service-url:
      defultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true   #set show ipadress
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    
microservice-serprovider-user-eurekaclient:   #be service project 's application.name
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
